### ISSUE TITLE
Fix typos and broken code

### ISSUE THREAD

**Issue by jonathan-lindqvist** [MSaurus/my-tab#23]
In the html head we have a link tag does not close.

The index.css have 6 errors.

And the js file is missing some semicolons.

Maybe create another issue for adding linting

**Comment by jonathan-lindqvist** [comment]
@MSaurus the css works atm and I dont know if it is just vs code giving warnings?

**Comment by MSaurus** [comment]
JS don't need semicolons right? Think we should agree to what we wanna use, but a lot of times it's optional if I remember right

**Comment by jonathan-lindqvist** [comment]
> 
> 
> JS don't need semicolons right? Think we should agree to what we wanna use, but a lot of times it's optional if I remember right

Ye, tou dont need them, but either way we should be consistent.

**Comment by MSaurus** [comment]
Agree, sooo what do you want? Do you want them or not? I'm okay both ways. 

And about the css warnings, that's most probably because of my old extension that hasn't been updated with the new standards and so on. The warnings will probably disappear if we decide to go on an independent compiler
