### ISSUE TITLE
New name and change title accordingly

### ISSUE THREAD

**Issue by jonathan-lindqvist** [MSaurus/my-tab#26]
Do we want to get a new name for the repo and product? Or should we stick with new-tab? 

Eitherway we need to change the title, or will that be handled for us by chrome and firefox?

**Comment by MSaurus** [comment]
We probably would like a new name for the project. I don't know how easy it is to change name later on when we published the extension. If it's easy and doesn't create any problem, then we could change it after that. Otherwise we need to come up with a name before we publish it
